In [1]:
import numpy as np

# Vector example
v = np.array([3, 2])
print("Vector:", v)

# Matrix example
A = np.array([[2, 0], [0, 3]])
print("Matrix A:\n", A)

# Matrix multiplication
result = A @ v
print("A @ v =", result)

Vector: [3 2]
Matrix A:
 [[2 0]
 [0 3]]
A @ v = [6 6]


In [2]:
# Dot product
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print("Dot product:", dot_product)
print("Also using @ operator:", a @ b)

Dot product: 32
Also using @ operator: 32


In [3]:
# Matrix transpose
B = np.array([[1, 2], [3, 4], [5, 6]])
print("Original matrix:\n", B)
print("\nTransposed:\n", B.T)

Original matrix:
 [[1 2]
 [3 4]
 [5 6]]

Transposed:
 [[1 3 5]
 [2 4 6]]


In [4]:
# Identity matrix
I = np.eye(3)
print("3x3 Identity matrix:\n", I)

3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
# Matrix inverse
C = np.array([[4, 7], [2, 6]])
C_inv = np.linalg.inv(C)
print("Original matrix:\n", C)
print("\nInverse matrix:\n", C_inv)
print("\nVerify (should give identity): \n", C @ C_inv)

Original matrix:
 [[4 7]
 [2 6]]

Inverse matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]

Verify (should give identity): 
 [[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]


In [9]:
#det6erminant

A = np.array([[1,2], [3,4]])
print (A)

[[1 2]
 [3 4]]


In [10]:
det = np.linalg.det(A)
print(det)

-2.0000000000000004
